[project]
name = "personal-library-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pymongo[srv]>=4.11.2",
    "python-dotenv>=1.0.1",
    "streamlit>=1.43.2",
]
